### ISSUE TITLE
DB에서 post(게시글) 가져올때 likes(게시글 좋아요 체크) 가져오는 방법 문의

### ISSUE THREAD

**Issue by Hong-Seungmin** [Hong-Seungmin/hanghae_chapter3_week2_myboard#2]
1. Likes.java
```java
@Entity
public class Likes {

    ...

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "PostId")
    private Post post;

    ...
```
2. Post.java
```java
@Entity
public class Post {

    ...

    @OneToMany(mappedBy = "post", cascade = CascadeType.ALL, orphanRemoval = true)
    @BatchSize(size = 50)
    private List<Likes> likeList = new ArrayList<>();

    ...
```

Post 를 가져올때는 항상 Post 객체에 해당하는 `List<Likes>` 를 가져와야하는 상황입니다.
(게시글을 읽을때는 좋아요 카운트가 표기되어야 합니다.)

생각없이 코드를 작성하다보니, 무심코 `@ManyToOne(fetch = FetchType.LAZY)`를 적었는데..
나중에 확인해보니 의심이 드네요.. "바로바로 써야하는 상황인데? 굳이 따로 쿼리를 날려야할까?"

아무쪼록 현재는 코드를 **EAGER**변경해두긴하였습니다.

다시 질문을 정리하자면,
1. Post와 Likes는 함께가져와서 바로 Post의 likeList의 size를 계산한다.
2. 일단 Post만 가져오고, 카운트를 세릴때 또 Likes를 가져온다.

3. BatchSize의 길이 적정수치는?

4. JPA에서 쿼리를 분할해서 요청하는 이유는 무엇일까요?

**Comment by salmon2** [comment]
일단 패치 타입에는 LAZY(지연) 타입과 EAGER(즉시) 타입이 존재합니다.
1. LAZY
post select 시 연관된 like는 프록시(가짜)객체로 like를 끌어 오고, like를 사용할 때 select가 호출
2. EAGER
post select 시 연관된 like를 where 문을 통하여 동시에 가져옵니다.
join을 통해서 sql 1개가 아니라 여러개 날라가는데 시점만 post select 시 한번에 가져오는 겁니다.
LAZY 등 EAGER 등 둘다 qeury가 2개 날라갑니다 시점만 다를 뿐이지

EAGER의 문제점
A 게시글 select -> 해당하는 like where post id = A 로 검색
근데 게시글 수가 100개면 100번의 like select가 발생합니다.
where post id = A
where post id = B
where post id = C ...

여기서 나온게 batchsize 이죠 
게시글이 만약에 1만개라면 post를 findAll 하면 1만개의 select * from like where postId = ...
가 발새애하는데 post를 batchsize 만큼 제한을 하니 그만큼 쿼리 수에 제한을 둡니다.

또한 후에 게시글 select를 다른 곳에 개발할 때 문제가 됩니다.
Eager로 만들어서 default로 like를 끌어 오니 기본적으로 sql이 2번나가고
like가 필요없는 개발을 할 때도 sql나가는 사태가 발생합니다.

또한 프로그래머가 의도치 않는 SQL이 나갈 확률이 높아 에러가 발생할 확률이 높습니다.
https://ict-nroo.tistory.com/132 한번 읽어보면 좋을 것 같습니다.

이를 해결할려면 JPQL로 쌩 sql문을 작성하여 join을 하면 될 것 같습니다.

**Comment by Hong-Seungmin** [comment]
오 좋은 답변 감사합니다!
궁금증이 해결되었네요.

결국 1건 조회면 EAGER로 하여도 무방하겠지만,
복수조회일 경우를 따지면 N+1 문제가 발생하기에 지연로딩을 하게되는 거네요.

Post 엔티티 같은 경우를 보면, 1건도 있고 복수 조회도 있으니..
굳이 제 의도대로 간다면,
별도의 1건 조회용 JPQL을 작성하여

1건 조회일 경우는  1건조회용 JPQL을 호출
복수 조회일 경우 findAll 을 하면되겠네요!

감사합니다!
